/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type {
  CreateProductDto,
  FindAllProductsResponseDto,
  Product,
  ProductFindAllParams,
  UpdateProductDto,
} from "./models";

import { customInstance } from "./http-client";
import type { BodyType } from "./http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get all products
 */
export const productFindAll = (
  params?: ProductFindAllParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<FindAllProductsResponseDto>(
    { url: `/api/products`, method: "GET", params },
    options,
  );
};
/**
 * @summary Create a new product
 */
export const productCreate = (
  createProductDto: BodyType<CreateProductDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  const formData = new FormData();
  formData.append("name", createProductDto.name);
  formData.append("description", createProductDto.description);
  formData.append("price", createProductDto.price.toString());
  if (createProductDto.discount !== undefined) {
    formData.append("discount", createProductDto.discount.toString());
  }
  formData.append("sku", createProductDto.sku);
  if (createProductDto.image !== undefined) {
    formData.append("image", createProductDto.image);
  }

  return customInstance<Product>(
    {
      url: `/api/products`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    },
    options,
  );
};
/**
 * @summary Get a single product by ID
 */
export const productFindOne = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Product>(
    { url: `/api/products/${id}`, method: "GET" },
    options,
  );
};
/**
 * @summary Update an existing product
 */
export const productUpdate = (
  id: number,
  updateProductDto: BodyType<UpdateProductDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  const formData = new FormData();
  if (updateProductDto.name !== undefined) {
    formData.append("name", updateProductDto.name);
  }
  if (updateProductDto.description !== undefined) {
    formData.append("description", updateProductDto.description);
  }
  if (updateProductDto.price !== undefined) {
    formData.append("price", updateProductDto.price.toString());
  }
  if (updateProductDto.discount !== undefined) {
    formData.append("discount", updateProductDto.discount.toString());
  }
  if (updateProductDto.sku !== undefined) {
    formData.append("sku", updateProductDto.sku);
  }
  if (updateProductDto.image !== undefined) {
    formData.append("image", updateProductDto.image);
  }

  return customInstance<Product>(
    {
      url: `/api/products/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
    },
    options,
  );
};
/**
 * @summary Delete a product by ID
 */
export const productRemove = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<Product>(
    { url: `/api/products/${id}`, method: "DELETE" },
    options,
  );
};
export type ProductFindAllResult = NonNullable<
  Awaited<ReturnType<typeof productFindAll>>
>;
export type ProductCreateResult = NonNullable<
  Awaited<ReturnType<typeof productCreate>>
>;
export type ProductFindOneResult = NonNullable<
  Awaited<ReturnType<typeof productFindOne>>
>;
export type ProductUpdateResult = NonNullable<
  Awaited<ReturnType<typeof productUpdate>>
>;
export type ProductRemoveResult = NonNullable<
  Awaited<ReturnType<typeof productRemove>>
>;
