/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { MinMaxRangeDtoResponse } from "./models";

import { customInstance } from "./http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get the minimum and maximum price of products
 */
export const filtersGetMinMaxRangePrice = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<MinMaxRangeDtoResponse>(
    { url: `/api/products-filters/min-max-range-price`, method: "GET" },
    options,
  );
};
export type FiltersGetMinMaxRangePriceResult = NonNullable<
  Awaited<ReturnType<typeof filtersGetMinMaxRangePrice>>
>;
