/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Name of the product
 * @maxLength 255
 */
export type CreateProductDtoName = { [key: string]: unknown };
