/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface CreateProductDto {
  /**
   * Name of the product
   * @maxLength 255
   */
  name: string;
  /** Description of the product */
  description: string;
  /**
   * Price of the product
   * @minimum 0
   */
  price: number;
  /**
   * Discounted price of the product
   * @minimum 0
   */
  discount?: number;
  /**
   * SKU of the product
   * @maxLength 100
   */
  sku: string;
  image?: Blob;
}
