/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * SKU of the product
 * @maxLength 100
 */
export type CreateProductDtoSku = { [key: string]: unknown };
