/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { CreateProductDtoName } from "./create-product-dto-name";
import type { CreateProductDtoDescription } from "./create-product-dto-description";
import type { CreateProductDtoPrice } from "./create-product-dto-price";
import type { CreateProductDtoDiscount } from "./create-product-dto-discount";
import type { CreateProductDtoSku } from "./create-product-dto-sku";

export interface CreateProductDto {
  /**
   * Name of the product
   * @maxLength 255
   */
  name: CreateProductDtoName;
  /** Description of the product */
  description: CreateProductDtoDescription;
  /**
   * Price of the product
   * @minimum 0
   */
  price: CreateProductDtoPrice;
  /**
   * Discounted price of the product
   * @minimum 0
   */
  discount?: CreateProductDtoDiscount;
  /**
   * SKU of the product
   * @maxLength 100
   */
  sku: CreateProductDtoSku;
  image?: Blob;
}
