/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Discounted price of the product
 * @minimum 0
 */
export type CreateProductDtoDiscount = { [key: string]: unknown };
