/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { MinMaxRangeDtoQuery } from "./min-max-range-dto-query";

export interface Filters {
  price?: MinMaxRangeDtoQuery;
}
