/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { Product } from "./product";
import type { PaginationMetadataDto } from "./pagination-metadata-dto";

export interface FindAllProductsResponseDto {
  /** list of Product items */
  data: Product[];
  meta: PaginationMetadataDto;
}
