/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export * from "./create-product-dto";
export * from "./create-product-dto-description";
export * from "./create-product-dto-discount";
export * from "./create-product-dto-name";
export * from "./create-product-dto-price";
export * from "./create-product-dto-sku";
export * from "./filters";
export * from "./find-all-products-response-dto";
export * from "./min-max-range-dto-query";
export * from "./min-max-range-dto-response";
export * from "./pagination-metadata-dto";
export * from "./product";
export * from "./product-find-all-params";
export * from "./product-find-all-sort-item";
export * from "./update-product-dto";
export * from "./update-product-dto-description";
export * from "./update-product-dto-discount";
export * from "./update-product-dto-name";
export * from "./update-product-dto-price";
export * from "./update-product-dto-sku";
