/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export * from "./create-product-dto";
export * from "./create-product-dto-description";
export * from "./create-product-dto-discount";
export * from "./create-product-dto-name";
export * from "./create-product-dto-price";
export * from "./create-product-dto-sku";
export * from "./object";
export * from "./product";
export * from "./product-discount";
export * from "./product-find-all-params";
export * from "./product-photo-file-name";
export * from "./update-product-dto";
export * from "./update-product-dto-description";
export * from "./update-product-dto-discount";
export * from "./update-product-dto-name";
export * from "./update-product-dto-price";
export * from "./update-product-dto-sku";
