/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface MinMaxRangeDtoQuery {
  /**
   * Minimum price filter
   * @minimum 0
   */
  min?: number;
  /**
   * Maximum price filter
   * @minimum 0
   */
  max?: number;
}
