/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface PaginationMetadataDto {
  /** Current page number */
  page: number;
  /** Number of items per page */
  limit: number;
  /** Total number of items */
  totalItemsCount: number;
  /** Total number of pages */
  totalPagesCount: number;
  /** Total number of pages */
  hasPreviousPage: boolean;
  hasNextPage: boolean;
}
