/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export type ProductFindAllSortItem =
  (typeof ProductFindAllSortItem)[keyof typeof ProductFindAllSortItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductFindAllSortItem = {
  "id:asc": "id:asc",
  "id:desc": "id:desc",
  "name:asc": "name:asc",
  "name:desc": "name:desc",
  "slug:asc": "slug:asc",
  "slug:desc": "slug:desc",
  "description:asc": "description:asc",
  "description:desc": "description:desc",
  "price:asc": "price:asc",
  "price:desc": "price:desc",
  "discount:asc": "discount:asc",
  "discount:desc": "discount:desc",
  "sku:asc": "sku:asc",
  "sku:desc": "sku:desc",
  "photoFileName:asc": "photoFileName:asc",
  "photoFileName:desc": "photoFileName:desc",
  "updatedAt:asc": "updatedAt:asc",
  "updatedAt:desc": "updatedAt:desc",
  "createdAt:asc": "createdAt:asc",
  "createdAt:desc": "createdAt:desc",
} as const;
