/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Discounted for price of the product
 * @minimum 0
 * @nullable
 */
export type ProductDiscount = { [key: string]: unknown } | null;
