/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

export interface Product {
  /** Unique identifier of the product */
  id: number;
  /**
   * Name of the product
   * @maxLength 255
   */
  name: string;
  /** Description of the product */
  description: string;
  /**
   * Price of the product
   * @minimum 0
   */
  price: number;
  /**
   * Discounted for price of the product
   * @minimum 0
   */
  discount: number;
  /**
   * SKU of the product
   * @maxLength 100
   */
  sku: string;
  /**
   * URL of the product photo
   * @nullable
   */
  photoFileName: string | null;
  /** Update product date */
  updatedAt: string;
  /** Create product date */
  createdAt: string;
}
