/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { ProductFindAllSortItem } from "./product-find-all-sort-item";
import type { Filters } from "./filters";

export type ProductFindAllParams = {
  /**
   * Current page number
   */
  page?: number;
  /**
   * Number of items per page
   */
  limit?: number;
  /**
   * Sort by property and order. Format: "property:order".
   */
  sort?: ProductFindAllSortItem[];
  /**
   * Фильтры для поиска продуктов
   */
  filters?: Filters;
};
