/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */
import type { Object } from "./object";

export type ProductFindAllParams = {
  /**
   * Filter products by fields (e.g., { name: "Product" })
   */
  filter: Object;
  /**
   * Sort by field and direction (e.g., name:ASC)
   */
  sort: string;
  /**
   * Limit the number of items per page
   */
  limit: number;
  /**
   * Page number
   */
  page: number;
};
