/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Документация
 * Документация к запросам
 * OpenAPI spec version: 1.0
 */

/**
 * Description of the product
 */
export type UpdateProductDtoDescription = { [key: string]: unknown };
